from GraphImplementation import UnDiGraph, DiGraph
from Algorithms import DFSAlgo, BFSAlgo, KosarajuSharir

graph = DiGraph('graph')
graph.add_node('a')
graph.add_node('b')
graph.add_node('c')
graph.add_node('d')
graph.add_node('e')
graph.add_node('f')
graph.add_node('g')
graph.add_node('h')
graph.add_edge('a', 'b')
graph.add_edge('b', 'e')
graph.add_edge('b', 'c')
graph.add_edge('b', 'f')
graph.add_edge('e', 'f')
graph.add_edge('e', 'a')
graph.add_edge('c', 'd')
graph.add_edge('c', 'g')
graph.add_edge('d', 'c')
graph.add_edge('d', 'h')
graph.add_edge('f', 'g')
graph.add_edge('g', 'f')
graph.add_edge('g', 'h')
graph.visualize()

dfs = DFSAlgo(graph)
dfs.run_algo()

ks = KosarajuSharir(graph)
ks.run_algo()

graph2 = UnDiGraph('undigraph')
graph2.add_node('a')
graph2.add_node('b')
graph2.add_node('c')
graph2.add_node('d')
graph2.add_node('e')
graph2.add_node('f')
graph2.add_node('g')
graph2.add_node('h')
graph2.add_edge('a', 'b')
graph2.add_edge('b', 'e')
graph2.add_edge('b', 'c')
graph2.add_edge('b', 'f')
graph2.add_edge('e', 'f')
graph2.add_edge('e', 'a')
graph2.add_edge('c', 'd')
graph2.add_edge('c', 'g')
graph2.add_edge('d', 'h')
graph2.add_edge('f', 'g')
graph2.add_edge('g', 'h')

bfs = BFSAlgo('a', graph2)
bfs.run_algo()
